const naruto = <String>[
  'Obito Uchiha',
  'Sasuke Uchiha',
  'Pain',
  'Nagato Uzumaki',
  'Jiraiya',
  'Tsunade',
  'Naruto Uzumaki',
  'Sakura Haruno',
  'Neji Hyuga',
  'Shikamaru Nara',
  'Madara Uchiha',
  'Itachi Uchiha',
  'Hashirama Senju',
  'Tobirama Senju',
  'Hiruzen Sarutobi',
  'Minato Namikaze',
  'Kushina Uzumaki',
  'Hinata Hyuga',
  'Ino Yamanaka',
  'Rock Lee',
  'Might Guy',
  'Killer Bee',
  'Kurama',
  'Kabuto Yakushi',
  'Gaara',
  'Temari',
  'Kakuzu',
  'Konan',
  'Sasori',
  'Orochiamru',
  'Danzo Hashimura',
  'Kakashi Hatake',
  'Yamato',
  'Sai Yamanaka',
  'Kisame Hoshigake',
  'Zabuza Momochi',
  'Haku',
  'Hidan',
  'Deidara',
];

const aot = [
  'Eren Jäger',
  'Zeke Jäger',
  'Grisha Jäger',
  'Eren Kruger',
  'Mikasa Ackerman',
  'Levi Ackerman',
  'Kenny Ackerman',
  'Armin Arlert',
  'Erwin Smith',
  'Hange Zöe',
  'Conny Springer',
  'Jean Kirstein',
  'Sasha Braus',
  'Reiner Braun',
  'Bertholdt Hoover',
  'Annie Leonhart',
  'Yelena',
  'Floch Forster',
  'Historia Reiss',
  'Ymir Fritz',
  'Pieck Finger',
  'Gabi Braun',
  'Falco Grice'
];

const deathNote = <String>[
  'Light Yagami',
  'L',
  'Near',
  'Mello',
  'Watari',
  'Soichiro Yagami',
  'Ryuk',
  'Rem',
  'Misa Amane',
  'Teru Mikami',
  'Kiyomi Takada',
  'Ray Penber',
  'Naomi Misora',
  'Touta Matsuda'
];

const jujutsuKaisen = <String>[
  'Yuji Itadori',
  'Saturo Gojo',
  'Ryomen Sukuna',
  'Suguru Geto',
  'Toji Fushiguro',
  'Megumi Fushiguro',
  'Maki Zenin',
  'Mai Zenin',
  'Aoi Todo',
  'Nobara Kugisaki',
  'Kento Nanami',
  'Mahito',
  'Kenjaku',
  'Jogo'
];

const others = [
  'Monkey D. Luffy',
  'Thorfinn',
  'Askeladd',
  'Thors',
  'Thorkell',
  'Canute',
  'Kaneki Ken',
  'Touka Kirishima',
  'Roronoa Zoro',
  'Nami',
  'Nico Robin',
  'Vinsmoke Sanji',
  'Osamu Dazai',
  'Tanjiro Kamado',
  'Denji',
  'Makima',
  'Boruto Uzumaki',
  'Sarada Uchiha',
  'Killua Zoldyck',
  'Kurapika',
  'Gon Freecss',
  'Hisoka Morrow',
  'Chrollo Lucifer',
  'Johan Liebert',
  'Anna Liebert',
  'Kenzo Tenma'
];